"""Create class model

Revision ID: 2acfebda7050
Revises:
Create Date: 2026-03-17 15:48:07.105367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2acfebda7050'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
                    sa.Column(
                        'id',
                        sa.Uuid(),
                        nullable=False
                    ),
                    sa.Column(
                        'name',
                        sa.String(length=100),
                        nullable=False
                    ),
                    sa.Column(
                        'subject',
                        sa.String(length=100),
                        nullable=False
                    ),
                    sa.Column(
                        'teacher_id',
                        sa.Uuid(),
                        nullable=False
                    ),
                    sa.Column(
                        'created_at',
                        sa.DateTime(),
                        nullable=False
                    ),
                    sa.Column(
                        'updated_at',
                        sa.DateTime(),
                        nullable=False
                    ),
                    sa.ForeignKeyConstraint(
                        ['teacher_id'],
                        ['user.id'],
                    ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_class_name'),
        'class',
        ['name'],
        unique=False
    )
    op.create_index(
        op.f('ix_class_subject'),
        'class',
        ['subject'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_subject'), table_name='class')
    op.drop_index(op.f('ix_class_name'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
