"""create student table

Revision ID: b3989f1dabf2
Revises: c46c30b6344e
Create Date: 2026-03-26 16:23:49.086090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b3989f1dabf2'
down_revision: Union[str, Sequence[str], None] = 'c46c30b6344e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profile',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),  # noqa
                    sa.Column('user_id', sa.Uuid(), nullable=False),    # noqa
                    sa.Column('roll_number', sa.Integer(), autoincrement=True, nullable=False),     # noqa
                    sa.Column('dues', sa.Integer(), autoincrement=False, nullable=True),        # noqa
                    sa.Column('pending_dues', sa.Integer(), autoincrement=False, nullable=True),    # noqa
                    sa.Column('is_active', sa.Boolean(), nullable=False),       # noqa
                    sa.Column('classes', sa.Uuid(), nullable=False),        # noqa
                    sa.Column('created_at', sa.DateTime(), nullable=False),     # noqa
                    sa.Column('left_class_at', sa.DateTime(), nullable=True),   # noqa
                    sa.ForeignKeyConstraint(['classes'], ['class.id'], ),   # noqa
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),    # noqa
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profile')
    # ### end Alembic commands ###
